# Generated by Django 4.1 on 2022-08-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0003_customer_order_alter_product_name_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table='orderItems',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='shipping_address',
            table='shipping_address',
        ),
    ]
