# Generated by Django 4.1 on 2022-08-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0004_alter_customer_table_alter_order_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shipping_address',
            new_name='Shippingaddress',
        ),
    ]
