# Generated by Django 4.1 on 2022-08-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0005_rename_shipping_address_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='myuser',
            new_name='user',
        ),
    ]
