# Generated by Django 4.1 on 2022-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0006_rename_myuser_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(choices=[('1', 'Delhi'), ('2', 'mumbai'), ('3', 'goa'), ('4', 'bihar'), ('5', 'Punjab'), ('7', 'Rajasthan')], default=1, max_length=50),
        ),
        migrations.AlterModelTable(
            name='orderitems',
            table=None,
        ),
    ]
