# Generated by Django 4.1 on 2022-08-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0007_alter_shippingaddress_state_alter_orderitems_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
