# Generated by Django 4.1 on 2022-08-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0008_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
