# Generated by Django 4.1 on 2022-08-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0013_alter_order_complete_alter_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
