# Generated by Django 4.1 on 2022-08-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapp', '0014_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingaddress',
            table=None,
        ),
    ]
